version: '3.5'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: hrm
    restart: unless-stopped
    env_file:
      - .env
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'