# Generated by Django 4.2.1 on 2023-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_remove_employee_email_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='uploads/employee/'),
        ),
    ]
