# Generated by Django 4.2.1 on 2023-06-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='employee/'),
        ),
    ]
