# Generated by Django 4.2.1 on 2023-06-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_alter_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc_no', models.CharField(max_length=50, null=True)),
                ('nrc_front', models.ImageField(upload_to='employee/identity/')),
                ('nrc_back', models.ImageField(upload_to='employee/identity/')),
                ('passport_no', models.CharField(max_length=50, null=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('passport_photo', models.ImageField(upload_to='employee/identity/')),
                ('remark', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
        ),
    ]
