# Generated by Django 4.2.1 on 2023-06-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_identity_family_record_alter_identity_passport_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name_plural': 'Identities'},
        ),
    ]
