# Generated by Django 4.2.1 on 2023-06-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_remove_employee_status'),
        ('hrm', '0007_alter_identity_options'),
    ]

    operations = [
    ]
