# Generated by Django 4.2.1 on 2023-06-06 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0008_merge_20230606_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identity',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee'),
        ),
    ]
