# Generated by Django 4.2.1 on 2023-06-06 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_alter_employee_user_alter_identity_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.payment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.position'),
        ),
    ]
