# Generated by Django 4.2.1 on 2023-06-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0012_alter_employee_payment_alter_employee_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='family_record',
            field=models.ImageField(blank=True, null=True, upload_to='employee/identity/'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='nrc_back',
            field=models.ImageField(blank=True, null=True, upload_to='employee/identity/'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='nrc_front',
            field=models.ImageField(blank=True, null=True, upload_to='employee/identity/'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='nrc_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='identity',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee/identity/'),
        ),
    ]
