# Generated by Django 4.2.1 on 2023-06-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0013_alter_identity_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='to_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='current_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
